In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
!pip install pandas

     ---------------------------------------- 10.9/10.9 MB 1.3 MB/s eta 0:00:00
     -------------------------------------- 500.7/500.7 kB 1.1 MB/s eta 0:00:00


In [4]:
import pandas as pd

In [8]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [9]:
arr1.ndim

1

In [15]:
 arr2=np.array([[1,2,3,4],[1,2,3,5]])
 arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 5]])

In [16]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)

2
(2, 4)
8


In [18]:
print(np.__version__)

1.23.4


In [19]:
print(arr2)

[[1 2 3 4]
 [1 2 3 5]]


In [20]:
type(arr2)

numpy.ndarray

In [29]:
import time
arr1=np.arange(15000)
arr2=np.arange(15000)
arr=time.time()
print (arr1+arr2)
print(time.time()- arr)

[    0     2     4 ... 29994 29996 29998]
0.0010051727294921875
